# Generated by Django 5.2 on 2025-04-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_image_url_post_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='example slug', unique=True),
            preserve_default=False,
        ),
    ]
