services:
  web:
    build: ./backend
    container_name: django_app
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DB_NAME=mydb
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_HOST=db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my_phpmyadmin
    restart: always
    ports:
      - "5000:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword

volumes:
  db_data:
