# Generated by Django 5.2 on 2025-07-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0002_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
